

const PRIORITY_MAP = {
  PRIORITY_SPAWN_HARVESTER: 95,
  PRIORITY_SPAWN_WORKER: 0,
  PRIORITY_SPAWN_CARRIER: 100,
  PRIORITY_SPAWN_UPGRADER: 50,
  PRIORITY_SPAWN_BUILDER: 40,
  PRIORITY_SPAWN_REPAIRER: 45,
  PRIORITY_SPAWN_MINER: 10,
  PRIORITY_SPAWN_BASE_TRANSFEROR: 60,
}


const C = {

  config: {
    SHOW_CPU_CREEPS: false,
    SHOW_CPU_BUILDINGS: false,
  },

  TIME_INTERVAL_COUNT_CREEPS: 10,

  TIME_INTERVAL_WALL_REPAIRER_RESELECT_TARGET: 500,

  TIME_INTERVAL_TOWER_REPIRE: 5,

  PRIORITY_SPAWN_HARVESTER: 95,
  PRIORITY_SPAWN_WORKER: 0,
  PRIORITY_SPAWN_CARRIER: 100,
  PRIORITY_SPAWN_UPGRADER: 50,
  PRIORITY_SPAWN_BUILDER: 40,
  PRIORITY_SPAWN_REPAIRER: 45,
  PRIORITY_SPAWN_MINER: 10,
  PRIORITY_SPAWN_BASE_TRANSFEROR: 60,

  //TODO role名改为用变量表示
  ROLE_TO_PRIORITY: {

    harvester: PRIORITY_MAP['PRIORITY_SPAWN_HARVESTER'],
    worker: PRIORITY_MAP['PRIORITY_SPAWN_WORKER'],
    carrier: PRIORITY_MAP['PRIORITY_SPAWN_CARRIER'],
    upgrader: PRIORITY_MAP['PRIORITY_SPAWN_UPGRADER'],
    builder: PRIORITY_MAP['PRIORITY_SPAWN_BUILDER'],
    repairer: PRIORITY_MAP['PRIORITY_SPAWN_REPAIRER'],
    miner: PRIORITY_MAP['PRIORITY_SPAWN_MINER'],
    base_transferor: PRIORITY_MAP['PRIORITY_SPAWN_BASE_TRANSFEROR'],

  },




  myName: 'Mofeng',

  RM: {
    CONTAINERS: 'containers',
    LINKS: 'link',

    SPAWN_QUEUE: 'spawnQueue',
  },

  IGNORE_CREEPS: true



}




module.exports = C